In [1]:
CREATE TABLE IF NOT EXISTS `lecteur` (
  `numlecteur` int(11) NOT NULL,
  `nomlecteur` varchar(30) DEFAULT NULL,
  `prenomlecteur` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`numlecteur`)
);

In [2]:
INSERT INTO `lecteur` (`numlecteur`, `nomlecteur`, `prenomlecteur`) VALUES
(13, 'ALAMARD', 'Frédéric'),
(14, 'BERTRAND', 'Carole'),
(15, 'SPAGUETTI', 'Soisic'),
(16, 'DUPUIS', 'Laurence'),
(17, 'BRULEY', 'Isvan'),
(18, 'ELAS', 'Ludivine'),
(19, 'FOUX', 'Eric'),
(21, 'INAUD', 'Bertrand'),
(22, 'AUAROT', 'Bernard'),
(23, 'KANST', 'Judith'),
(24, 'LEROI', 'Vincent'),
(25, 'HAMSI', 'Mathieu'),
(26, 'NICOLAS', 'Louis'),
(27, 'OUATE', 'Caroline'),
(28, 'PARIS', 'Effel'),
(29, 'KOI', 'Fleur'),
(30, 'SEMIEU', 'Georges'),
(31, 'SUIE', 'Noël'),
(32, 'TAROD', 'Adage'),
(33, 'URBAIN', 'Jean-Bernard'),
(34, 'VAZI', 'Franc'),
(36, 'XEROX', 'Frank'),
(37, 'YOYO', 'Tata'),
(43, 'FAIDEUX', 'Nicolas'),
(44, 'DUPUIS', 'Marie'),
(45, 'ESTER', 'Quentin'),
(46, 'SIDAMPOULE', 'Michel'),
(47, 'SALAMON', 'Erchad');

In [3]:
CREATE TABLE IF NOT EXISTS `ouvrage` (
  `numouvrage` int(11) NOT NULL,
  `titreouvrage` varchar(50) DEFAULT NULL,
  `anneeparution` int(11) DEFAULT NULL,
  PRIMARY KEY (`numouvrage`)
);

In [4]:
INSERT INTO `ouvrage` (`numouvrage`, `titreouvrage`, `anneeparution`) VALUES
(1, 'Passeport pour l''algorithmique objet', 1998),
(2, 'Technologie des ordinateurs et des réseaux', 2000),
(3, 'Instances en ADA', 1990),
(4, 'Le tout en poche : La base de registres (W5 & NT4)', 1998),
(5, 'Le tout en poche : Linux', 2000),
(6, 'Dépanner & revitaliser un PC', 1998),
(7, 'Systèmes d''exploitation', 1994),
(8, 'Assembleur facile', 1989),
(9, 'La maîtrise du MS-DOS et du BIOS', 1989),
(10, 'C Facile', 1989),
(11, 'Visual Basic guide de référence', 1999),
(12, 'VB 6 Les bases de données et SQL Server 7', 2000),
(13, 'Turbo Pascal 5 Manuel de référence', 1988),
(14, 'Livre d''or Visual C++ 4.0', 1995),
(15, 'VB et SQL Serveur Guide tout-terrain', 1996),
(16, 'Access 2000 Manuel du Développeur', 1999),
(17, 'Le grand livre du C++', 1993),
(18, 'Dictionnaire d''informatique', 2001),
(19, 'AMC*Designor 6 Guide de l''utilisateur', 1998),
(20, 'Ingénierie des systèmes d''information MERISE II', 1998),
(21, 'VB 6 Le guide du programmeur', 1999),
(22, 'Technologie des ordinateurs', 1992),
(23, 'Le RNIS techniques et atouts', 1990),
(24, 'Modélisation objet avec UML', 2001),
(25, 'Formation à Visual C++', 2003),
(26, 'Manager .net', 2002),
(27, 'PHP Professionnel', 2001),
(28, 'Le guide de l''utilisateur UML', 2001),
(29, 'Le registre Windows XP', 2003),
(30, 'Le tout en poche : Flash 5', 2001),
(31, 'JavaScript Professionnel', 2001),
(32, 'Solution .net : XML', 2001),
(34, 'Merise/2 Modèles et techniques avancés', 2000),
(35, 'Programmez en C#', 2003),
(36, 'Les outils pour Visual .NET', 2002),
(37, 'Merise Sujets corrigés', 2001),
(38, 'Intelligence artificielle 2°édition', 2006);

In [5]:
CREATE TABLE IF NOT EXISTS `emprunter` (
  `numlecteur` int(11) NOT NULL,
  `numouvrage` int(11) NOT NULL,
  `dateemprunt` date NOT NULL,
  `dateretour` date DEFAULT NULL,
  PRIMARY KEY (`numlecteur`,`numouvrage`,`dateemprunt`),
  FOREIGN KEY (`numlecteur`) REFERENCES `lecteur` (`numlecteur`),
  FOREIGN KEY (`numouvrage`) REFERENCES `ouvrage` (`numouvrage`)
);

In [6]:
INSERT INTO `emprunter` (`numlecteur`, `numouvrage`, `dateemprunt`, `dateretour`) VALUES
(13, 17, '2024-03-19', NULL),
(15, 11, '2024-03-06', '2023-03-16'),
(15, 21, '2024-03-06', NULL),
(21, 10, '2024-02-18', NULL),
(21, 30, '2022-07-17', '2021-07-26'),
(25, 2, '2022-12-08', '2022-01-08'),
(25, 2, '2023-01-13', '2022-01-23'),
(25, 6, '2024-02-25', NULL),
(25, 20, '2023-12-14', '2023-01-09'),
(30, 17, '2024-01-23', '2023-03-09'),
(30, 25, '2024-01-23', NULL);

## R01 : Qui est le lecteur n°25 ?

In [16]:
SELECT numlecteur, nomlecteur, prenomlecteur
FROM lecteur
WHERE numlecteur = 25

numlecteur	nomlecteur	prenomlecteur
25	HAMSI	Mathieu

## R02 : Liste des lecteurs dont le nom de famille commence par la lettre « A »

In [23]:
SELECT numlecteur, nomlecteur, prenomlecteur
FROM lecteur
WHERE nomlecteur LIKE "A%";

numlecteur	nomlecteur	prenomlecteur
13	ALAMARD	Frédéric
22	AUAROT	Bernard

## R03 : Liste des ouvrages qui traitent de la méthode Merise.

In [35]:
SELECT titreouvrage
FROM ouvrage
WHERE titreouvrage LIKE "%Merise%";

titreouvrage
Ingénierie des systèmes d'information MERISE II
Merise/2 Modèles et techniques avancés
Merise Sujets corrigés

## R04 : Liste des ouvrages qui traitent du « registre » à partir de l’année 2000.

In [38]:
SELECT titreouvrage, anneeparution
FROM ouvrage
WHERE anneeparution > 2000
AND titreouvrage LIKE "%registre%";

titreouvrage	anneeparution
Le registre Windows XP	2003

## R05 : Liste des lecteurs qui portent le nom (ou le prénom) « BERTRAND »

In [40]:
SELECT numlecteur, nomlecteur, prenomlecteur
FROM lecteur
WHERE nomlecteur LIKE "%BERTRAND%"
OR prenomlecteur LIKE "%BERTRAND%";

numlecteur	nomlecteur	prenomlecteur
14	BERTRAND	Carole
21	INAUD	Bertrand

## R06 : Titre des ouvrages actuellement empruntés ou ayant déjà été empruntés.

In [48]:
SELECT numouvrage, dateemprunt, dateretour
FROM emprunter
WHERE dateretour IS NULL;

numouvrage	dateemprunt	dateretour
17	2024-03-19
21	2024-03-06
10	2024-02-18
6	2024-02-25
25	2024-01-23

## R07 : Nom des lecteurs ayant effectué au moins un emprunt depuis le début de l’année 2024.

In [51]:
SELECT numlecteur, numouvrage, dateemprunt, dateretour
FROM emprunter
WHERE dateemprunt LIKE "%2024%"

Error: ambiguous column name: numouvrage

Error: